stages:
  - build
  - test
  - deploy

default:
  image: node:20-alpine

build_admin: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "starting script"
    - apk add --no-cache --virtual .build-deps alpine-sdk
    - npm install -g pnpm
    - pnpm install
    - echo "starting blog build"
    - pnpm run build --filter admin
    - echo "build complete"
test_admin:
  stage: test
  needs: [build_admin]
  script:
    - echo "This job tests something."

deploy_admin:
  stage: deploy
  needs: [test_admin]
  script:
    - echo "This job deploys something."
