stages:
  - build
  - test
  - deploy

default:
  image: node:20-alpine

build_storefront: # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "starting script"
    - apk add --no-cache --virtual .build-deps alpine-sdk
    - npm install -g pnpm
    - pnpm install
    - echo "starting storefront build"
    - pnpm run build --filter storefront
    - echo "build complete"
test_storefront:
  stage: test
  needs: [build_storefront]
  script:
    - echo "This job tests something."

deploy_storefront:
  stage: deploy
  needs: [test_storefront]
  script:
    - echo "This job deploys something."
